//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Snooping.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Follows
    {
        public int UserFollowerID { get; set; }
        public int UserFollowedID { get; set; }
        public System.DateTime DateFollow { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual UserProfile UserProfile1 { get; set; }
    }
}
