//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MardomEvaluationTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Snoops
    {
        public int SnoopID { get; set; }
        public string Snoop { get; set; }
        public Nullable<System.Guid> ImageGuid { get; set; }
        public System.DateTime DateSnoop { get; set; }
    }
}
