//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MardomEvaluationTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsersInfo
    {
        public int UserInfoID { get; set; }
        public int Age { get; set; }
        public string EMail { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime DateModified { get; set; }
        public bool Status { get; set; }
        public int UserID { get; set; }
        public string FullName { get; set; }
        public byte[] Photo { get; set; }
    
        public virtual UserProfile UserProfile { get; set; }
        public virtual FollowsCount FollowsCount { get; set; }
    }
}
