//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MardomEvaluationTest.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public UserProfile()
        {
            this.webpages_Roles = new HashSet<webpages_Roles>();
            this.Snoops = new HashSet<Snoops>();
            this.UsersInfo = new HashSet<UsersInfo>();
            this.Follows = new HashSet<Follows>();
            this.Follows1 = new HashSet<Follows>();
        }
    
        public int UserID { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
        public virtual ICollection<Snoops> Snoops { get; set; }
        public virtual ICollection<UsersInfo> UsersInfo { get; set; }
        public virtual ICollection<Follows> Follows { get; set; }
        public virtual ICollection<Follows> Follows1 { get; set; }
    }
}
